"""initial schema baseline

Revision ID: 00950ecca438
Revises: 
Create Date: 2026-03-19 00:45:43.911755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00950ecca438'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('test_case_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'test_case_code', name='uq_test_case_code')
    )
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(length=50), nullable=False),
    sa.Column('parsed_snapshot', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_label', name='uq_document_version_label')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_uploaded_by_user_id'), 'document_versions', ['uploaded_by_user_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('requirement_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_section', sa.String(length=255), nullable=True),
    sa.Column('source_block_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'requirement_code', name='uq_requirement_code')
    )
    op.create_index(op.f('ix_requirements_document_id'), 'requirements', ['document_id'], unique=False)
    op.create_table('compare_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('compare_status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compare_runs_source_version_id'), 'compare_runs', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_compare_runs_target_version_id'), 'compare_runs', ['target_version_id'], unique=False)
    op.create_index(op.f('ix_compare_runs_triggered_by_user_id'), 'compare_runs', ['triggered_by_user_id'], unique=False)
    op.create_table('document_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('block_key', sa.String(length=255), nullable=False),
    sa.Column('block_type', sa.String(length=100), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('normalized_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'block_key', name='uq_document_block_key')
    )
    op.create_index(op.f('ix_document_blocks_document_version_id'), 'document_blocks', ['document_version_id'], unique=False)
    op.create_table('requirement_test_case_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'test_case_id', name='uq_requirement_test_case')
    )
    op.create_index(op.f('ix_requirement_test_case_mappings_requirement_id'), 'requirement_test_case_mappings', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_test_case_mappings_test_case_id'), 'requirement_test_case_mappings', ['test_case_id'], unique=False)
    op.create_table('change_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compare_run_id', sa.Integer(), nullable=False),
    sa.Column('source_version_id', sa.Integer(), nullable=False),
    sa.Column('target_version_id', sa.Integer(), nullable=False),
    sa.Column('source_block_id', sa.Integer(), nullable=True),
    sa.Column('target_block_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['compare_run_id'], ['compare_runs.id'], ),
    sa.ForeignKeyConstraint(['source_block_id'], ['document_blocks.id'], ),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['target_block_id'], ['document_blocks.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_items_assignee_user_id'), 'change_items', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_change_items_compare_run_id'), 'change_items', ['compare_run_id'], unique=False)
    op.create_index(op.f('ix_change_items_review_status'), 'change_items', ['review_status'], unique=False)
    op.create_index(op.f('ix_change_items_source_block_id'), 'change_items', ['source_block_id'], unique=False)
    op.create_index(op.f('ix_change_items_source_version_id'), 'change_items', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_change_items_target_block_id'), 'change_items', ['target_block_id'], unique=False)
    op.create_index(op.f('ix_change_items_target_version_id'), 'change_items', ['target_version_id'], unique=False)
    op.create_table('ai_review_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_item_id', sa.Integer(), nullable=False),
    sa.Column('suggested_assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('recommended_review_status', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('draft_comment', sa.Text(), nullable=True),
    sa.Column('suggested_checks', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_item_id'], ['change_items.id'], ),
    sa.ForeignKeyConstraint(['suggested_assignee_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_item_id', name='uq_change_item_ai_review_draft')
    )
    op.create_index(op.f('ix_ai_review_drafts_change_item_id'), 'ai_review_drafts', ['change_item_id'], unique=False)
    op.create_index(op.f('ix_ai_review_drafts_generation_status'), 'ai_review_drafts', ['generation_status'], unique=False)
    op.create_index(op.f('ix_ai_review_drafts_suggested_assignee_user_id'), 'ai_review_drafts', ['suggested_assignee_user_id'], unique=False)
    op.create_table('change_item_requirement_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_item_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['change_item_id'], ['change_items.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_item_id', 'requirement_id', name='uq_change_item_requirement')
    )
    op.create_index(op.f('ix_change_item_requirement_links_change_item_id'), 'change_item_requirement_links', ['change_item_id'], unique=False)
    op.create_index(op.f('ix_change_item_requirement_links_requirement_id'), 'change_item_requirement_links', ['requirement_id'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_item_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['change_item_id'], ['change_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_author_user_id'), 'review_comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_review_comments_change_item_id'), 'review_comments', ['change_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_change_item_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_author_user_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_change_item_requirement_links_requirement_id'), table_name='change_item_requirement_links')
    op.drop_index(op.f('ix_change_item_requirement_links_change_item_id'), table_name='change_item_requirement_links')
    op.drop_table('change_item_requirement_links')
    op.drop_index(op.f('ix_ai_review_drafts_suggested_assignee_user_id'), table_name='ai_review_drafts')
    op.drop_index(op.f('ix_ai_review_drafts_generation_status'), table_name='ai_review_drafts')
    op.drop_index(op.f('ix_ai_review_drafts_change_item_id'), table_name='ai_review_drafts')
    op.drop_table('ai_review_drafts')
    op.drop_index(op.f('ix_change_items_target_version_id'), table_name='change_items')
    op.drop_index(op.f('ix_change_items_target_block_id'), table_name='change_items')
    op.drop_index(op.f('ix_change_items_source_version_id'), table_name='change_items')
    op.drop_index(op.f('ix_change_items_source_block_id'), table_name='change_items')
    op.drop_index(op.f('ix_change_items_review_status'), table_name='change_items')
    op.drop_index(op.f('ix_change_items_compare_run_id'), table_name='change_items')
    op.drop_index(op.f('ix_change_items_assignee_user_id'), table_name='change_items')
    op.drop_table('change_items')
    op.drop_index(op.f('ix_requirement_test_case_mappings_test_case_id'), table_name='requirement_test_case_mappings')
    op.drop_index(op.f('ix_requirement_test_case_mappings_requirement_id'), table_name='requirement_test_case_mappings')
    op.drop_table('requirement_test_case_mappings')
    op.drop_index(op.f('ix_document_blocks_document_version_id'), table_name='document_blocks')
    op.drop_table('document_blocks')
    op.drop_index(op.f('ix_compare_runs_triggered_by_user_id'), table_name='compare_runs')
    op.drop_index(op.f('ix_compare_runs_target_version_id'), table_name='compare_runs')
    op.drop_index(op.f('ix_compare_runs_source_version_id'), table_name='compare_runs')
    op.drop_table('compare_runs')
    op.drop_index(op.f('ix_requirements_document_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_document_versions_uploaded_by_user_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
